=== Discordier/Contao-ER3/doc/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.contao.org/extension"
	xmlns:ctx="http://www.contao.org/extension" elementFormDefault="qualified">

	<element name="extension">
		<complexType>
			<sequence>
				<element name="title" type="ctx:text"
					maxOccurs="unbounded">
					<annotation>
						<documentation>
							title of the extension.
						</documentation>
					</annotation>
				</element>
				<element name="subtitle" type="ctx:text" minOccurs="1"
					maxOccurs="unbounded">
					<annotation>
						<documentation>
							subtitle of the extension.
						</documentation>
					</annotation>
				</element>
				<element name="description" type="ctx:text"
					minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>
							description of the extension.
						</documentation>
					</annotation>
				</element>
				<element name="logo" type="ctx:image" maxOccurs="1"
					minOccurs="0">
					<annotation>
						<documentation>logo of the extension.</documentation>
					</annotation>
				</element>
				<element name="licence" type="ctx:license" minOccurs="0"
					maxOccurs="unbounded">
					<annotation>
						<documentation>
							license the extension is subject to.
						</documentation>
					</annotation>
				</element>
				<element name="author" type="ctx:identity" minOccurs="0"
					maxOccurs="unbounded">
					<annotation>
						<documentation>
							authors that have contributed to the extension.
						</documentation>
					</annotation>
				</element>
				<element name="copyright" type="ctx:identity"
					minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>
							copyright holder for the extension.
						</documentation>
					</annotation>
				</element>
				<element name="link" type="ctx:link" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>
							URL of the issue tracker for the extension.
						</documentation>
					</annotation>
				</element>
				<element name="dependencies" minOccurs="0"
					maxOccurs="unbounded" type="ctx:dependencies">
					<annotation>
						<documentation>
							dependencies for the extension.
						</documentation>
					</annotation>
				</element>
				<element name="conflicts" minOccurs="0"
					maxOccurs="unbounded" type="ctx:conflicts">
					<annotation>
						<documentation>
							conflicts for the extension.
						</documentation>
					</annotation>
				</element>
				<element name="pefers" minOccurs="0"
					maxOccurs="unbounded" type="ctx:pefers">
					<annotation>
						<documentation>
							suggestions and optional dependencies for the extension.
						</documentation>
					</annotation>
				</element>
                <element name="installer" type="ctx:class" minOccurs="0">
					<annotation>
						<documentation>
							name of the class that handles installation, uninstallation and upgrade tasks
						</documentation>
					</annotation>
				</element>
                <element name="upgrade" type="ctx:upgrade"
					maxOccurs="unbounded" minOccurs="0">
					<annotation>
						<documentation>specification of the upgradeability from older versions.</documentation>
					</annotation>
				</element>
				<element name="downgrade" type="ctx:downgrade"
					maxOccurs="unbounded" minOccurs="0">
					<annotation>
						<documentation>specification of the downgradeability to older versions.</documentation>
					</annotation>
				</element>
			</sequence>
			<attribute name="name" type="token" use="required">
				<annotation>
					<documentation>uniqe name of the extension.</documentation>
				</annotation>
			</attribute>
			<attribute name="version" type="ctx:version" use="required">
				<annotation>
					<documentation>version of the extension.</documentation>
				</annotation>
			</attribute>
			<attribute name="encrypted" type="boolean" use="optional" default="false">
				<annotation>
					<documentation>define if files in CONTAO and DATA are encrypted. See chapter "Licensing" from the rfccc-1 for more details!</documentation>
				</annotation>
			</attribute>
		</complexType>
	</element>

	<simpleType name="version">
		<annotation>
			<documentation>version string - see RFCCC1.</documentation>
		</annotation>
		<restriction base="string">
			<pattern
				value="(\d+)\.(\d+)(\.\d+)?([-\.][a-z]*\d*)?((\.head\.(\w+)|(\.(alpha|a|beta|b|rc|stable)\d*)?\.(\d+)))">
			</pattern>
		</restriction>
	</simpleType>

	<simpleType name="versionCompare">
		<annotation>
			<documentation>version string for comparing of versions.</documentation>
		</annotation>
		<restriction base="string">
			<pattern
				value="(\d+)(\.\d+)?(\.\d+)?([-\.][a-z]*\d*)?(\.(head\.(\w+)|(alpha|a|beta|b|rc|stable)\d*\.(\d+)))?">
			</pattern>
		</restriction>
	</simpleType>

	<complexType name="text">
		<annotation>
			<documentation>text in a defined language.</documentation>
		</annotation>
		<simpleContent>
			<extension base="string">
				<attribute name="language" use="optional" type="language">
					<annotation>
						<documentation>the language the text is written in - if omitted, 'en' is used.</documentation>
					</annotation>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="link">
		<sequence>
			<element name="description" type="ctx:text" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>description what the link defines.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="href" use="required" type="ctx:url">
			<annotation>
				<documentation>the hyperref URL.</documentation>
			</annotation>
		</attribute>
		<attribute name="rel" use="required">
			<annotation>
				<documentation>
					defines the nature of the link.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<enumeration value="homepage">
						<annotation>
							<documentation>
								link to a homepage.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="snapshot">
						<annotation>
							<documentation>
								link to a snapshot.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="screencast">
						<annotation>
							<documentation>
								link to a screencast.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="video">
						<annotation>
							<documentation>
								link to a video.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="help">
						<annotation>
							<documentation>
								link to general help.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="faq">
						<annotation>
							<documentation>link to FAQ.</documentation>
						</annotation>
					</enumeration>
					<enumeration value="manual">
						<annotation>
							<documentation>
								link to manual.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="forum">
						<annotation>
							<documentation>
								link to bulletin board discussion.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="tracker">
						<annotation>
							<documentation>
								link to issue tracker.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="scm">
						<annotation>
							<documentation>link to scm.</documentation>
						</annotation>
					</enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="language" type="language" use="optional">
			<annotation>
				<documentation>
					defines the language of the link target. i.e. for 
					defining links to a manual in different languages.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<simpleType name="url">
		<annotation>
			<documentation>An URL.</documentation>
		</annotation>
		<restriction base="string">
			<pattern value=".*">
			</pattern>
		</restriction>
	</simpleType>

	<complexType name="identity">
		<annotation>
			<documentation>a private or business identity.
			</documentation>
		</annotation>
		<attribute name="name" use="required" type="string">
			<annotation>
				<documentation>Personal or business name. i.e. John Doe or Acme Inc.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="type" use="optional" default="personal">
			<simpleType>
				<restriction base="string">
					<enumeration value="personal">
						<annotation>
							<documentation>This identity represents a person.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="group">
						<annotation>
							<documentation>This idenity represents a group.
							</documentation>
						</annotation>
					</enumeration>
					<enumeration value="company">
						<annotation>
							<documentation>This identity represents a business.
							</documentation>
						</annotation>
					</enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="email" use="optional" type="string">
			<annotation>
				<documentation>E-Mail address for contact.</documentation>
			</annotation>
		</attribute>
		<attribute name="url" use="optional" type="string">
			<annotation>
				<documentation>Homepage for contact.</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="license">
		<attribute name="name" use="required" type="string">
			<annotation>
				<documentation>Name of the license, i.e. LGPL3</documentation>
			</annotation>
		</attribute>
		<attribute name="file" use="optional" type="string">
			<annotation>
				<documentation>file with the license text. If this is not specified, 
					a file LICENCE_X will be searched, whereby X is the name of the 
					license i.e. LICENCE_LGPL3. 
					The license file must be delivered along with the extension.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="relation">
		<sequence>
			<element name="version" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>The version(s) of a referenced extension.
					</documentation>
				</annotation>
				<complexType>
					<attribute name="match" type="ctx:versionCompare">
						<annotation>
							<documentation>exact match of the version.</documentation>
						</annotation>
					</attribute>
					<attribute name="lowest" type="ctx:versionCompare">
						<annotation>
							<documentation>lowest matching version (including the version itself).</documentation>
						</annotation>
					</attribute>
					<attribute name="highest" type="ctx:versionCompare">
						<annotation>
							<documentation>highest matching version (excluding the version itself).</documentation>
						</annotation>
					</attribute>
				</complexType>
			</element>
			<element name="description" type="ctx:text" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>Description of the reference. Here one can define 
						why the dependency/conflict exists or why an extension is suggested for installation.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" use="required" type="string">
			<annotation>
				<documentation>Name of the extension that is being referenced.
				</documentation>
			</annotation>
		</attribute>
	</complexType>
	
	<complexType name="dependencies">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="dependency"
				type="ctx:relation">
				<annotation>
					<documentation>Dependency on an extension.</documentation>
				</annotation>
			</element>
			<element name="group">
				<annotation>
					<documentation>a group of dependencies of an extension.</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element minOccurs="0" maxOccurs="unbounded" name="dependency"
							type="ctx:relation">
							<annotation>
								<documentation>Alternative dependency within the current group.</documentation>
							</annotation>
						</element>
					</sequence>
					<attribute name="preferation" type="token" use="required">
						<annotation>
							<documentation>space seperated list of the unique names of the dependencies highest order preference first.</documentation>
						</annotation>
					</attribute>
				</complexType>
			</element>
		</choice>
	</complexType>

	<complexType name="conflicts">
		<choice>
			<element minOccurs="0" maxOccurs="unbounded" name="conflict"
				type="ctx:relation">
				<annotation>
					<documentation>conflict to an extension.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>

	<complexType name="pefers">
		<choice>
			<element minOccurs="0" maxOccurs="unbounded" name="prefer"
				type="ctx:relation">
				<annotation>
					<documentation>suggest another extension to be installed along with the current one.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	
    <complexType name="upgrade">
    	<annotation>
    		<documentation>
    			Defines the upgradability for the current version from previous versions on.
    		</documentation>
    	</annotation>
    	<sequence>
    		<element name="description" type="ctx:text" maxOccurs="unbounded" minOccurs="0">
    			<annotation>
    				<documentation>Description of the upgradability.</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="version" type="ctx:versionCompare" use="required">
    		<annotation>
    			<documentation>The oldest version this rule applies to.</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="userdata" type="ctx:userdata" default="partial" />
    </complexType>

    <complexType name="downgrade">
    	<annotation>
    		<documentation>
    			Defines the downgradability for the current version to previous versions.
    		</documentation>
    	</annotation>
    	<sequence>
    		<element name="description" type="ctx:text" maxOccurs="unbounded" minOccurs="0">
    			<annotation>
    				<documentation>Description of the downgradability.</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="version" type="ctx:versionCompare" use="required">
    		<annotation>
    			<documentation>
    				The youngest version this rule applies to.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="userdata" type="ctx:userdata" default="partial" />
    </complexType>

	<simpleType name="userdata">
		<restriction base="string">
			<enumeration value="lossless">
				<annotation>
					<documentation>Upgrade/downgrade can savely be done without data loss.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="dropUnused">
				<annotation>
					<documentation>Upgrade/downgrade will drop unused data.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="partial">
				<annotation>
					<documentation>Upgrade/downgrade will drop user data. i.e. deletion of a feature.</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
   	
    <simpleType name="class">
    	<restriction base="string">
    		<pattern value="[a-zA-Z_][a-zA-Z0-9_]*(\\[a-zA-Z_][a-zA-Z0-9_]*)*"></pattern>
    	</restriction>
    </simpleType>

    <complexType name="image">
    	<choice>
    		<element name="url" type="ctx:url">
    			<annotation>
    				<documentation>External URL to the image.</documentation>
    			</annotation>
    		</element>
    		<element name="binary">
    			<annotation>
    				<documentation>The image embedded as base64 coding.</documentation>
    			</annotation>
    			<complexType>
    				<simpleContent>
    					<extension base="base64Binary">
    						<attribute name="type">
    							<annotation>
    								<documentation>Defines the binary type of the image.</documentation>
    							</annotation>
    							<simpleType>
    								<restriction base="string">
    									<enumeration value="image/png">
    										<annotation>
    											<documentation>PNG</documentation>
    										</annotation>
    									</enumeration>
    									<enumeration value="image/jpeg">
    										<annotation>
    											<documentation>JPEG</documentation>
    										</annotation>
    									</enumeration>
    									<enumeration value="image/gif">
    										<annotation>
    											<documentation>GIF</documentation>
    										</annotation>
    									</enumeration>
    								</restriction>
    							</simpleType>
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</choice>
    </complexType>
</schema>

=== Discordier/Contao-ER3/doc/extension.xml
<?xml version="1.0" encoding="UTF-8"?>
<ctx:extension name="MyContaoExtension" version="1.2.3"
	xmlns:ctx="http://www.contao.org/extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.contao.org/extension extension.xsd ">
	
	<ctx:title>A real cool Contao extension.</ctx:title>
	<ctx:title language="de">Eine wirklich tolle Contao Erweiterung.</ctx:title>
	
	<ctx:subtitle>Extends Contao with realy cool new features.</ctx:subtitle>
	<ctx:subtitle language="de">Erweitert Contao mit wirklich tollen neuen Funktionen.</ctx:subtitle>
	
	<ctx:description>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mattis, nisi molestie vulputate imperdiet, ipsum massa consectetur nibh, id suscipit nibh libero eu augue. Etiam hendrerit interdum arcu et tristique. Curabitur turpis felis, vehicula sed condimentum nec, vestibulum sed odio. Cras eget est at purus egestas convallis quis non purus. Aliquam tortor nulla, suscipit id iaculis in, convallis eu est. Aliquam cursus egestas orci, at faucibus erat luctus sed. Vestibulum egestas vestibulum ligula, quis porta elit tempus nec. Maecenas eget felis purus.</ctx:description>
	<ctx:description language="de">Quisque vel elementum diam. Integer felis enim, iaculis in adipiscing eget, consequat sit amet est. Nunc auctor iaculis lacus, sed pretium leo hendrerit sit amet. Maecenas erat tellus, vulputate eget placerat semper, accumsan nec nulla. Maecenas eros elit, dapibus egestas commodo aliquet, iaculis ut nibh. Nam in nibh id nunc lacinia placerat. Cras at turpis lacus, a mattis diam. Etiam nec consectetur quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec convallis nisl sollicitudin sem cursus luctus. Quisque quis enim est, eu ultrices magna.</ctx:description>
	
	<ctx:logo>
		<ctx:binary type="image/png">iVBORw0KGgoAAAANSUhEUgAAALoAAAC6AQMAAAAjwMWyAAAABlBMVEX///8AAABVwtN+AAABAUlEQVRYhe2WQQrFIAxEBzyAR/LqHskDFPyTxNpC/z5TaBCpeV3YTJ0IfPH6aJMxcABltGKLqQDgqaNOZstYmXQQ6zk7aucbc+gAbrezlGJgpXRASGuiWhEfmicBPwatxHicjySwwwD+RQaw7RbfsRlH7RwCwCws5jgMkACNKfoFjYyDwVkC+P7IyowKNgEArouJag2puMwCgEX0PjTsAfc/MRXAFY1uFAJLANcy+pBt9+a7maCGpbrPrvtEOjgFNrNwLAGuVrTmZ4/KADBjxdmw27G/IBXExWtLexVRALi9+g+3iygA1mXCb88KwKW1lB0DGhkkQBwDTyHEFQBfvDp+Boph7kWA6dAAAAAASUVORK5CYII=</ctx:binary>
	</ctx:logo>
	
	<ctx:licence name="LGPL3" file="LGPL3.txt" />
	
	<ctx:author name="Tristan Lins" email="tristan.lins@infinitysoft.de"
		url="http://www.infinitysoft.de" />
		
	<ctx:copyright name="InfinitySoft 2011" type="company" email="info@infinitysoft.de"
		url="http://www.infinitysoft.de" />
	
	<ctx:link rel="homepage" href="http://www.contao.org">
		<ctx:description>Official project homepage.</ctx:description>
		<ctx:description language="de">Offizielle Projekthomepage.</ctx:description>
	</ctx:link>
	<ctx:link rel="manual" href="http://www.contao.org/dokumentation.html" language="de">
		<ctx:description>Offizielles Benutzerhandbuch.</ctx:description>
	</ctx:link>
	<ctx:link rel="manual" href="http://www.contao.org/documentation.html" language="en">
		<ctx:description>Official User-Manual.</ctx:description>
	</ctx:link>
	<ctx:link rel="help" href="http://de.contaowiki.org" language="de">
		<ctx:description>Inoffizielles Wiki.</ctx:description>
	</ctx:link>
	<ctx:link rel="help" href="http://en.contaowiki.org" language="en">
		<ctx:description>Inofficial Wiki.</ctx:description>
	</ctx:link>
	<ctx:link rel="video" href="http://www.youtube.com/watch?feature=player_embedded&amp;v=8HkQVmfjjYc">
		<ctx:description>Introduction into TypoLIGHT/Contao.</ctx:description>
		<ctx:description language="de">Einfuehrung in TypoLIGHT/Contao.</ctx:description>
	</ctx:link>
	<ctx:link rel="forum" href="http://www.contao-community.de" language="de">
		<ctx:description>German contao community.</ctx:description>
		<ctx:description language="de">Deutsche Contao Community.</ctx:description>
	</ctx:link>
	<ctx:link rel="tracker" href="http://dev.contao.org">
		<ctx:description>Official bug and issue tracker.</ctx:description>
		<ctx:description language="de">Offizieller Bug und Issue Tracker.</ctx:description>
	</ctx:link>
	<ctx:link rel="scm" href="http://svn.contao.org">
		<ctx:description>Official svn repository.</ctx:description>
		<ctx:description language="en">Offizielles SVN Repository.</ctx:description>
	</ctx:link>
	
	<ctx:dependencies>
		<ctx:dependency name="contao">
			<ctx:version lowest="3.1" />
			<ctx:description>I need some features, that are new in version 3.1!</ctx:description>
			<ctx:description language="de">Es werden einige Funktionen benoetigt, die erst in Version 3.1 eingefuehrt wurden.</ctx:description>
		</ctx:dependency>
		<ctx:group>
			<ctx:dependency name="php:soap">
				<ctx:description>I love soap, thats because i need this php extension.</ctx:description>
				<ctx:description language="de">Ich liebe SOAP, deshalb benoetige ich diese PHP Komponente.</ctx:description>
			</ctx:dependency>
			<ctx:dependency name="nusoap">
				<ctx:description>If you dont have soap, I pleased with an alternative implementation.</ctx:description>
				<ctx:description language="de">Wenn dir SOAP fehlt, begnuege ich mich mit einer alternativen Implementierung.</ctx:description>
			</ctx:dependency>
		</ctx:group>
		<ctx:dependency name="pear:Mail">
			<ctx:version match="1.2"/>
			<ctx:description>I love mails, i want to send some!</ctx:description>
			<ctx:description language="de">Ich liebe Mails, deshalb will ich welche verschicken.</ctx:description>
		</ctx:dependency>
	</ctx:dependencies>
	<ctx:conflicts>
		<ctx:conflict name="db:mysql">
			<ctx:version match="4"/>
			<ctx:version lowest="5" highest="5.1"/>
			<ctx:version lowest="5.2"/>
			<ctx:description>I am sorry, but i only support MySQL 5.1.</ctx:description>
			<ctx:description language="de">Ich bin untroestlich, aber ich unterstuetzte nur MySQL 5.1!</ctx:description>
		</ctx:conflict>
	</ctx:conflicts>
	<ctx:pefers>
		<ctx:prefer name="MyOtherContaoExtension">
			<ctx:version match="1.5" />
			<ctx:description>This extension is prefered, but has no new stuff.</ctx:description>
			<ctx:description language="de">Die Erweiterung wird empfohlen, besitzt aber keine neuen Funktionen.</ctx:description>
		</ctx:prefer>
		<ctx:prefer name="MyThirdContaoExtension">
			<ctx:description>I prever this extension because it gives you a lot more features.</ctx:description>
			<ctx:description language="de">Ich empfehle diese Erweiterung weil sie noch mehr neue Funktionen mit sich bringt.</ctx:description>
		</ctx:prefer>
	</ctx:pefers>
	
	<ctx:installer>MyExtension\Installer</ctx:installer>
	
	<ctx:upgrade version="1.0" userdata="lossless">
		<ctx:description>You can upgrade from version 1.0.0 with no problems.</ctx:description>
		<ctx:description language="de">Sie koennen von Version 1.0.0 ohne Probleme aktualisieren.</ctx:description>
	</ctx:upgrade>
	<ctx:upgrade version="0" userdata="partial">
		<ctx:description>An upgrade from a development version is not realy supported. You may have to check your settings.</ctx:description>
		<ctx:description language="de">Ein Update von einer Entwicklungsversion wird nicht unterstuetzt. Sie muessen moeglicherweise alle Einstellungen ueberpruefen.</ctx:description>
	</ctx:upgrade>
	
	<ctx:downgrade version="1.2" userdata="lossless">
		<ctx:description>A downgrade is absolutely possible.</ctx:description>
		<ctx:description language="de">Ein Downgrade ist garantiert moeglich.</ctx:description>
	</ctx:downgrade>
	<ctx:downgrade version="1.1" userdata="dropUnused">
		<ctx:description>A downgrade to this version can be done without lossing your user data.</ctx:description>
		<ctx:description language="de">Ein Downgrade zu dieser Version kann ohne Nutzdatenverlust durchgefuehrt werden.</ctx:description>
	</ctx:downgrade>
	<ctx:downgrade version="1.0" userdata="partial">
		<ctx:description>You lose some of your user data, that is not supported by this old version.</ctx:description>
		<ctx:description>Sie werden einige Ihrer Nutzdaten verlieren, weil diese von der Version noch nicht unterstuetzt wurden.</ctx:description>
	</ctx:downgrade>
</ctx:extension>
